/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2020-08-03 05:56:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class iIntroduction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("/*課題００３　商品一覧とこだわりを作成*/\r\n");
      out.write("    \r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html>\r\n");
      out.write("            <head>\r\n");
      out.write("                <link rel=\"stylesheet\" href= \"02-02slist.css\">\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <title>動物サーバー/職業一覧</title>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <header>\r\n");
      out.write("                    <div id = \"topphoto\">\r\n");
      out.write("                        <h1 Style =\"padding-top: 15px;\"><img src=\"Picture/肉球.png\" width=\"40px\" Style =\"height:40px\" >動物サーバー</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </header>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"gnavi\">\r\n");
      out.write("                    <div class=\"gnavi\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <td class=\"gmavi_td\"><a href=\"notice.html\">お知らせ</a></td>\r\n");
      out.write("                            <td class=\"gmavi_td\"><a href=\"introduction.jsp\">サーバー紹介</a></td>\r\n");
      out.write("                            <td class=\"gmavi_td\"><a href=\"community.jsp\">コミュニティ</a></td>\r\n");
      out.write("                            <td class=\"gmavi_td\"><a href=\"connection.html\">接続方法</a></td>\r\n");
      out.write("                            <td class=\"gmavi_td\"><a href=\"01menberlist.html\">運営紹介</a></td>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"main\">\r\n");
      out.write("                    <h2 class=\"list_main_h2\">”動物サーバー”へようこそ！</h2>\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            動物サーバーはPVE、職業,そしてmcMMOによるサバイバル生活が送れます\r\n");
      out.write("                            また、ギルドに所属して仲間と共に冒険や他ギルドと決闘をして賞金を手にしたり、生産をしてお金を稼ぐことができます\r\n");
      out.write("                            </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <table><!--列ごとに幅を設定-->\r\n");
      out.write("                        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col height=\"500px\" 　align=\"left\">\r\n");
      out.write("                                <col width=\"100px\">\r\n");
      out.write("                                <col width=\" 50px\">\r\n");
      out.write("                                <col width=\"300px\">\r\n");
      out.write("                                </colgroup> \r\n");
      out.write("                            <td><img  src=\"iceimg/きこり1.png\"></td>\r\n");
      out.write("                            <td>木こり</td>\r\n");
      out.write("                            <td>★★★★☆ 4.51　</td>\r\n");
      out.write("                            <td>伐採すると通常より多くお金がもらえる</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/工事中１.png\"></td>\r\n");
      out.write("                            <td>鉱夫</td>\r\n");
      out.write("                            <td>★★★☆☆ 3.79　</td>\r\n");
      out.write("                            <td>採掘すると通常より多くお金がもらえる。<br>また、レアリティの高い鉱石ほど多くもらえる</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/酪農家.png\"></td>\r\n");
      out.write("                            <td>農民</td>\r\n");
      out.write("                            <td>★★★★☆ 4.34</td>\r\n");
      out.write("                            <td>作物を収穫すると通常より多くお金を得る。<br>しかし、他の職業と比べ安い</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/釣り人.png\"></td>\r\n");
      out.write("                            <td>釣り師</td>\r\n");
      out.write("                            <td>★★☆☆☆ 2.04　</td>\r\n");
      out.write("                            <td>熟練度が上がるとレアリティの高いアイテムが釣りやすくなり、ゴミが釣れにくくなる</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        \r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"list_main_h2\">中級者向け</h2>\r\n");
      out.write("                    <table><!--列ごとに幅を設定-->\r\n");
      out.write("                        <col width=\"100\" align=\"left\">\r\n");
      out.write("                        <col width=\"100\"><col width=\"50\">\r\n");
      out.write("                        <col width=\"300\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/調教師.png\"></td>\r\n");
      out.write("                            <td>調教師</td>\r\n");
      out.write("                            <td>★★★☆☆ 3.29　</td>\r\n");
      out.write("                            <td>ペットを捕獲、調教し能力を向上させることができる。<br>また、調教師のみ捕まえたペットは販売することができる</td>\r\n");
      out.write("                        </tr>    \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/店員.png\"></td>\r\n");
      out.write("                            <td>商売</td>\r\n");
      out.write("                            <td>★★★★☆ 4.56　</td>\r\n");
      out.write("                            <td>手に入れたアイテムを売ることができる。</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"list_main_h2\">上級者向け</h2>\r\n");
      out.write("                    <table><!--列ごとに幅を設定-->\r\n");
      out.write("                        <col width=\"100\" align=\"left\">\r\n");
      out.write("                        <col width=\"100\"><col width=\"50\">\r\n");
      out.write("                        <col width=\"300\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/司祭.png\"></td>\r\n");
      out.write("                            <td>司祭</td>\r\n");
      out.write("                            <td>★★★☆☆ 3.05　</td>\r\n");
      out.write("                            <td>エンチャントをすることでお金を得る<br>レアリティと需要が高いほど売れる</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/錬金術師.png\"></td>\r\n");
      out.write("                            <td>錬金術師</td>\r\n");
      out.write("                            <td>★★★★☆ 4.30　</td>\r\n");
      out.write("                            <td>ポーションを作成することでお金を得る<br>単価が一番高いが、材料収集が困難</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/ハンター.png\"></td>\r\n");
      out.write("                            <td>ハンター</td>\r\n");
      out.write("                            <td>★★☆☆☆ 2.45　</td>\r\n");
      out.write("                            <td>敵を討伐すると通常より多くお金を得る<br>また、防具や武器にボーナスが入る</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <h2 class=\"list_main_h2\">その他</h2>\r\n");
      out.write("                    <table><!--列ごとに幅を設定-->\r\n");
      out.write("                        <col width=\"100\" align=\"left\">\r\n");
      out.write("                        <col width=\"100\"><col width=\"50\">\r\n");
      out.write("                        <col width=\"300\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img  src=\"iceimg/犯罪者.png\"></td>\r\n");
      out.write("                            <td>指名手配</td>\r\n");
      out.write("                            <td>☆☆☆☆☆ 0　</td>\r\n");
      out.write("                            <td>主に荒らしが付く職業でペナルティがかかる<br>イベントの場合はPVPや盗みが可能となる</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        <footer>Copyright &copy;船橋あいす工房, all rights reserved.</footer>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
